/*
 * Generated by ISE 25.02.9.8732 - win64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F256_5990();
extern void F258_6152();
extern void F256_5994();
extern void F259_6156();
extern void F261_6320();
extern void F259_6161();
extern void F380_3837();
extern void F285_5836();
extern void F126_1487();
extern EIF_REFERENCE F126_1474();
extern EIF_BOOLEAN F126_1486();
extern EIF_BOOLEAN F126_1494();
extern void F126_1496();
extern void F126_1497();
extern void F126_1498();
extern void F67_1145();
extern EIF_TYPED_VALUE F67_1146();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F256_5990;
	egc_immstr8make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F256_5994;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F259_6156;
	egc_immstr32make_from_c_byte_array = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F259_6161;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F380_3837;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F258_6152;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F261_6320;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F285_5836;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F126_1487;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F126_1486;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F126_1474;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F126_1494;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F126_1496;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F126_1497;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F126_1498;

	egc_str_dtype = 257;

	egc_immstr8_dtype = 256;

	egc_str32_dtype = 260;

	egc_immstr32_dtype = 259;
	egc_arr_dtype = 379;
	egc_tup_dtype = 209;
	egc_disp_rout_id = 2110;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x0159;
	egc_sp_wchar = 0x01F2;
	egc_sp_bool = 0x0133;
	egc_sp_uint8 = 0x0216;
	egc_sp_uint16 = 0x035D;
	egc_sp_uint32 = 0x025A;
	egc_sp_uint64 = 0x01CD;
	egc_sp_int8 = 0x0315;
	egc_sp_int16 = 0x02F1;
	egc_sp_int32 = 0x01B9;
	egc_sp_int64 = 0x0339;
	egc_sp_real32 = 0x02A9;
	egc_sp_real64 = 0x02CD;
	egc_sp_pointer = 0x027D;
	egc_sp_ref = 0x017E;

	egc_uint8_dtype = 232;
	egc_uint16_dtype = 229;
	egc_uint32_dtype = 226;
	egc_uint64_dtype = 223;
	egc_int8_dtype = 220;
	egc_int16_dtype = 217;
	egc_int32_dtype = 214;
	egc_int64_dtype = 211;
	egc_bool_dtype = 247;
	egc_real32_dtype = 235;
	egc_char_dtype = 244;
	egc_wchar_dtype = 241;
	egc_real64_dtype = 238;
	egc_point_dtype = 250;

	egc_exception_dtype = 85;
	egc_except_emnger_dtype = 125;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "simple_cli";
	egc_system_location = "D:\\prod\\simple_cli\\EIFGENs\\simple_cli_tests\\W_code";
	egc_compiler_tag = 39;
	egc_project_version = 1765234183;
	egc_has_old_special_semantic = 0;
	scount = 988;

	egc_rcount = 3;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "CLI_TEST_APP.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 888;
	egc_rcarg[0] = 0;
	
	egc_rlist[1] = "EQA_EVALUATOR.make";
	egc_rcdt[1] = 0;
	egc_rcrid[1] = 2681;
	egc_rcarg[1] = 0;
	
	egc_rlist[2] = "ITP_INTERPRETER.execute";
	egc_rcdt[2] = 0;
	egc_rcrid[2] = 5090;
	egc_rcarg[2] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 66;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F67_1145;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F67_1146;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 46; /* CLI_TEST_APP */
	}if (egc_rcdt[1] == 0) {
		egc_rcdt[1] = 179; /* EQA_EVALUATOR */
	}if (egc_rcdt[2] == 0) {
		egc_rcdt[2] = 278; /* ITP_INTERPRETER */
	}
}

#ifdef __cplusplus
}
#endif
